In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset = pd.read_csv('F:\DESKTOP FOLDERS\FULL MACHINE LEARNING\model_selection\Machine Learning A-Z (Model Selection)\Regression\Data.csv')

In [3]:
dataset

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [4]:
X = dataset.iloc[:,0:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [6]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [7]:
#splitting the dataset into the training set and the test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size = 0.2, random_state = 1)

In [8]:
print(X_train)

[[   6.61   38.91 1015.77   92.31]
 [  22.72   65.61 1014.64   70.53]
 [  10.06   39.61 1018.22   70.22]
 ...
 [  18.59   39.54 1008.56   68.61]
 [  22.96   45.01 1012.21   50.81]
 [  20.5    49.69 1009.6    70.81]]


In [9]:
print(X_test)

[[  17.93   44.63 1003.54   87.41]
 [  16.34   42.28 1008.08   52.8 ]
 [  25.97   70.32 1007.48   57.01]
 ...
 [  10.68   38.38 1020.79   72.33]
 [  34.03   73.56 1006.49   51.07]
 [  15.28   44.58 1016.45   83.07]]


In [10]:
print(y_train)

[484.32 449.04 471.86 ... 462.56 450.37 452.94]


In [11]:
print(y_test)

[458.96 463.29 435.27 ... 476.22 440.29 467.92]


In [12]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

regressor.fit(X_train, y_train)

LinearRegression()

In [13]:
y_pred = regressor.predict(X_test)

In [14]:
np.set_printoptions(precision = 2)

In [15]:
y_pred = y_pred.reshape(-1,1)
print(y_pred)

[[457.26]
 [466.72]
 [440.37]
 ...
 [476.41]
 [424.62]
 [463.91]]


In [16]:
#visualising the results

print(np.concatenate((y_pred, y_test.reshape(len(y_test),1)),1 )) 

[[457.26 458.96]
 [466.72 463.29]
 [440.37 435.27]
 ...
 [476.41 476.22]
 [424.62 440.29]
 [463.91 467.92]]


In [17]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9321860060402447