In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset = pd.read_csv('F:\DESKTOP FOLDERS\FULL MACHINE LEARNING\model_selection\Machine Learning A-Z (Model Selection)\Regression\Data.csv')

In [3]:
X = dataset.iloc[:,0:-1].values
y = dataset.iloc[:,-1].values

In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size = 0.2, random_state = 1)

In [7]:
print(X_train)

[[   6.61   38.91 1015.77   92.31]
 [  22.72   65.61 1014.64   70.53]
 [  10.06   39.61 1018.22   70.22]
 ...
 [  18.59   39.54 1008.56   68.61]
 [  22.96   45.01 1012.21   50.81]
 [  20.5    49.69 1009.6    70.81]]


In [8]:
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train,y_train)

DecisionTreeRegressor(random_state=0)

In [9]:
np.set_printoptions(precision = 2)

In [10]:
y_pred = regressor.predict(X_test)

In [11]:
y_pred = y_pred.reshape(-1,1)
print(y_pred)

[[459.65]
 [462.26]
 [436.03]
 ...
 [477.18]
 [432.78]
 [468.23]]


In [12]:
print(np.concatenate((y_pred, y_test.reshape(len(y_test),1)),1 )) 

[[459.65 458.96]
 [462.26 463.29]
 [436.03 435.27]
 ...
 [477.18 476.22]
 [432.78 440.29]
 [468.23 467.92]]


In [13]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9342783714449767